### ISSUE TITLE
npm install command failure

### ISSUE THREAD

**Issue by LeoMingo** [yahoo/pure-site#358] opened 2017-02-05 04:48 UTC
After I git clone-ed pure-site repository into my computer, cd into pure-site then ran npm install command following README instruction, it returned an error message as follows:

`
npm WARN deprecated express-annotations@0.1.0: No compatible with ExpressJS 4.x Router
npm WARN deprecated express-yui@1.4.1: YUI library is no longer actively maintained
npm WARN deprecated express-map@0.1.0: No compatible with ExpressJS 4.x Router
npm ERR! git clone git@github.com:github:ericf/css-mediaquery Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-github-ericf-css-mediaquery-54df4a47'...
npm ERR! git clone git@github.com:github:ericf/css-mediaquery Permission denied (publickey).
npm ERR! git clone git@github.com:github:ericf/css-mediaquery fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:github:ericf/css-mediaquery 
npm ERR! git clone git@github.com:github:ericf/css-mediaquery Please make sure you have the correct access rights
npm ERR! git clone git@github.com:github:ericf/css-mediaquery and the repository exists.
npm ERR! notarget No compatible version found: css-mediaquery@'github:ericf/css-mediaquery#umd'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.0","0.1.0","0.1.1","0.1.2"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 4.0.0-kali1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/user/Documents/Projects/webs/pure-site
npm ERR! node -v v4.6.1
npm ERR! npm -v 1.4.21
npm ERR! code ETARGET
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/Documents/Projects/webs/pure-site/npm-debug.log
npm ERR! not ok code 0
`

**Comment by redonkulus** [comment] 2017-02-05 17:09
Looks like a duplicate of #357. I also left a comment you can check out https://github.com/yahoo/pure-site/issues/357#issuecomment-277533162

**Closed by redonkulus** 2017-02-05 17:09 UTC

**Comment by LeoMingo** [comment] 2017-02-06 13:20
Thanks
