### ISSUE TITLE
Header of marketing example 

### ISSUE THREAD

**Issue by fliiiix** [yahoo/pure-site#311] opened 2015-03-23 18:48 UTC
![2015-03-23--1427136273_1600x900](https://cloud.githubusercontent.com/assets/1682954/6787805/72b3d3e0-d195-11e4-9d81-4a64e6ea1c56.png)

Shouldn't be the brand on the same height as the menu items?

**Comment by jamesalley** [comment] 2015-03-23 18:57
Yes. It's a bug! Thank you for the report.

**Comment by jamesalley** [comment] 2015-06-08 21:42
Duplicate of #246

**Closed by jamesalley** 2015-06-08 21:42 UTC
Labels: bug
