### ISSUE TITLE
I don't understand the meaning of "*display: inline;"?

### ISSUE THREAD

**Issue by starlightme** [yahoo/pure-site#324] opened 2016-02-12 06:41 UTC
Excuse me, I feel quite confused about the css code in [blog layout](http://purecss.io/layouts/blog/)

```css
.nav-item {
    display: inline-block;
    *display: inline;  /*what is *display ?*/
    zoom: 1;
}
```

Could you explain it for me? Thanks a lot!

**Comment by lkraav** [comment] 2016-02-12 08:35
Duplicate of https://github.com/yahoo/pure/issues/553

**Closed by lkraav** 2016-02-12 08:35 UTC
